Change to cite definition
CurbSafeCharmer/refill pull request #63
Opened 2020-05-29 00:40 UTC by KeithDwiki

Hello, there has been a change to the cite templates on wikipedia. The parameter deadurl has been replaced by url-status. The values for this being 'dead' or 'live'.

This modification is to implement this change but is untested as I cannot workout how to set-up for testing.

2022-05-24 14:19 UTC, theresnotime requested changes

2022-05-24 14:19 UTC, theresnotime commented on backend/refill/formatters/citetemplate.py
> +    def _fragment_url-status(self, template, citation):
Invalid function name

2023-06-04 23:47 UTC, GlazerMann commented
This does not work, and should be closed.  A new and better pull request has been made by me.

2023-06-05 00:11 UTC, GlazerMann commented
@KeithDwiki This does not work, and should be closed. A new and better pull request has been made by me.

2023-06-05 19:55 UTC, closed without merging